#!/bin/bash

## Description: Sync public files from Production to DDEV
## Usage: sync-files-public
## Example: ddev sync-files-public

projectType=${DDEV_PROJECT_TYPE}

if [[ $projectType == "drupal8" || $projectType == "drupal9" || $projectType == "drupal10" ]]; then
  pathProd="@self.live:%files"
  pathDev="@self.dev:%files"
fi

if [[ $projectType == "drupal7" ]]; then
  pathProd="@live:%files"
  pathDev="@dev:%files"
fi

ddev drush rsync $pathProd $pathDev -v
