#!/bin/bash

## Description: Sync DB, public and private files from Production to DDEV
## Usage: sync-all
## Example: ddev sync-all

echo y | ddev sync-db

echo y | ddev sync-files-public

echo y | ddev sync-files-private
