#!/bin/bash

## Description: Sync private files from Production to DDEV
## Usage: sync-files-private
## Example: ddev sync-files-private

projectType=${DDEV_PROJECT_TYPE}

if [[ $projectType == "drupal8" || $projectType == "drupal9" || $projectType == "drupal10" || $projectType == "drupal" ]]; then
  pathProd="@self.live:%private"
  pathDev="@self.dev:%private"
fi

if [[ $projectType == "drupal7" ]]; then
  pathProd="@live:%private"
  pathDev="@dev:%private"
fi

ddev drush rsync $pathProd $pathDev -v
