#!/bin/bash

## Description: Sync DB from Production to DDEV
## Usage: sync-db
## Example: ddev sync-db

projectType=${DDEV_PROJECT_TYPE}

if [[ $projectType == "drupal8" || $projectType == "drupal9" || $projectType == "drupal10" ]]; then
  pathProd="@self.live"
  pathDev="@self.dev"
fi

if [[ $projectType == "drupal7" ]]; then
  pathProd="@live"
  pathDev="@dev"
fi

ddev drush sql-sync $pathProd $pathDev -v
