#!/bin/bash

## Description: Sync public files from Production to DDEV
## Usage: sync-files-public
## Example: ddev sync-files-public

projectType=${DDEV_PROJECT_TYPE}

excludePaths="js:css:styles:php:languages:translations:sync"

if [[ $projectType == "drupal8" || $projectType == "drupal9" || $projectType == "drupal10" || $projectType == "drupal" ]]; then
  pathProd="@self.live:%files"
  pathDev="@self.dev:%files"
fi

if [[ $projectType == "drupal7" ]]; then
  pathProd="@live:%files"
  pathDev="@dev:%files"
fi

ddev drush --exclude-paths=$excludePaths rsync $pathProd $pathDev -v
